import type { 
  Student, 
  StudentGroup, 
  Grade, 
  Attendance, 
  Contract, 
  Payment, 
  Subject, 
  Teacher, 
  Exam,
  Diploma,
  DashboardStats,
  ChartData,
} from '@/types'

// Performance Record interface
export interface PerformanceRecord {
  id: string
  student_id: string
  student_name: string
  student_photo: string
  subject_id: string
  subject_name: string
  semester: number
  education_year: string
  midterm_score: number
  current_score: number
  final_exam_score: number
  total_score: number
  grade: string
  credit: number
  status: string
  created_at: string
  updated_at: string
}

// ============================================
// MOCK STUDENTS
// ============================================

export const mockStudents: Student[] = [
  {
    id: '1',
    student_id_number: '210101001',
    first_name: 'Abdullayev',
    second_name: 'Akmal',
    third_name: 'Anvarovich',
    full_name: 'Abdullayev Akmal Anvarovich',
    birth_date: '2003-05-15',
    gender: 'male',
    citizenship: 'UZ',
    passport_number: 'AC1234567',
    phone: '+998901234567',
    email: 'akmal.abdullayev@univer.uz',
    address: 'Toshkent sh., Yunusobod t., 12-uy',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Akmal',
    education_type: 'full_time',
    education_form: 'budget',
    level: 'bachelor',
    course: 3,
    semester: 5,
    group_id: '1',
    group_name: '310-22',
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    status: 'active',
    enrollment_date: '2021-09-01',
    gpa: 4.2,
    total_credits: 105,
    debt_count: 0,
    created_at: '2021-09-01T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
  {
    id: '2',
    student_id_number: '210101002',
    first_name: 'Karimova',
    second_name: 'Madina',
    third_name: 'Rustamovna',
    full_name: 'Karimova Madina Rustamovna',
    birth_date: '2003-08-22',
    gender: 'female',
    citizenship: 'UZ',
    passport_number: 'AC2345678',
    phone: '+998902345678',
    email: 'madina.karimova@univer.uz',
    address: 'Toshkent sh., Chilonzor t., 8-uy',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Madina',
    education_type: 'full_time',
    education_form: 'contract',
    level: 'bachelor',
    course: 3,
    semester: 5,
    group_id: '1',
    group_name: '310-22',
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    status: 'active',
    enrollment_date: '2021-09-01',
    gpa: 4.5,
    total_credits: 110,
    debt_count: 0,
    created_at: '2021-09-01T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
  {
    id: '3',
    student_id_number: '220101003',
    first_name: 'Yusupov',
    second_name: 'Bobur',
    third_name: 'Shavkatovich',
    full_name: 'Yusupov Bobur Shavkatovich',
    birth_date: '2004-03-10',
    gender: 'male',
    citizenship: 'UZ',
    passport_number: 'AC3456789',
    phone: '+998903456789',
    email: 'bobur.yusupov@univer.uz',
    address: 'Toshkent sh., Mirzo Ulugbek t., 5-uy',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bobur',
    education_type: 'full_time',
    education_form: 'budget',
    level: 'bachelor',
    course: 2,
    semester: 3,
    group_id: '2',
    group_name: '220-23',
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    status: 'active',
    enrollment_date: '2022-09-01',
    gpa: 3.8,
    total_credits: 65,
    debt_count: 1,
    created_at: '2022-09-01T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
  {
    id: '4',
    student_id_number: '210201001',
    first_name: 'Nurmatova',
    second_name: 'Dilnoza',
    third_name: 'Bakhtiyorovna',
    full_name: 'Nurmatova Dilnoza Bakhtiyorovna',
    birth_date: '2003-11-30',
    gender: 'female',
    citizenship: 'UZ',
    passport_number: 'AC4567890',
    phone: '+998904567890',
    email: 'dilnoza.nurmatova@univer.uz',
    address: 'Toshkent sh., Yakkasaroy t., 15-uy',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dilnoza',
    education_type: 'full_time',
    education_form: 'contract',
    level: 'bachelor',
    course: 3,
    semester: 5,
    group_id: '3',
    group_name: '311-22',
    specialty_code: '5350500',
    specialty_name: 'Axborot xavfsizligi',
    department: 'Axborot xavfsizligi',
    faculty: 'Informatika va dasturlash',
    status: 'active',
    enrollment_date: '2021-09-01',
    gpa: 4.7,
    total_credits: 115,
    debt_count: 0,
    created_at: '2021-09-01T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
  {
    id: '5',
    student_id_number: '230101001',
    first_name: 'Toshmatov',
    second_name: 'Sardor',
    third_name: 'Erkinovich',
    full_name: 'Toshmatov Sardor Erkinovich',
    birth_date: '2005-02-14',
    gender: 'male',
    citizenship: 'UZ',
    passport_number: 'AC5678901',
    phone: '+998905678901',
    email: 'sardor.toshmatov@univer.uz',
    address: 'Toshkent sh., Sergeli t., 20-uy',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sardor',
    education_type: 'full_time',
    education_form: 'budget',
    level: 'bachelor',
    course: 1,
    semester: 1,
    group_id: '4',
    group_name: '110-24',
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    status: 'active',
    enrollment_date: '2024-09-01',
    gpa: 4.0,
    total_credits: 15,
    debt_count: 0,
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
]

// ============================================
// MOCK GROUPS
// ============================================

export const mockGroups: StudentGroup[] = [
  {
    id: '1',
    name: '310-22',
    course: 3,
    semester: 5,
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    education_type: 'full_time',
    education_form: 'budget',
    level: 'bachelor',
    curator_id: '1',
    curator_name: 'Raximov Sherzod Akbarovich',
    student_count: 25,
    active: true,
    created_at: '2022-09-01T00:00:00Z',
  },
  {
    id: '2',
    name: '220-23',
    course: 2,
    semester: 3,
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    education_type: 'full_time',
    education_form: 'budget',
    level: 'bachelor',
    curator_id: '2',
    curator_name: 'Karimova Feruza Bakhtiyorovna',
    student_count: 28,
    active: true,
    created_at: '2023-09-01T00:00:00Z',
  },
  {
    id: '3',
    name: '311-22',
    course: 3,
    semester: 5,
    specialty_code: '5350500',
    specialty_name: 'Axborot xavfsizligi',
    department: 'Axborot xavfsizligi',
    faculty: 'Informatika va dasturlash',
    education_type: 'full_time',
    education_form: 'contract',
    level: 'bachelor',
    curator_id: '3',
    curator_name: 'Yusupov Jamshid Ergashevich',
    student_count: 22,
    active: true,
    created_at: '2022-09-01T00:00:00Z',
  },
  {
    id: '4',
    name: '110-24',
    course: 1,
    semester: 1,
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    education_type: 'full_time',
    education_form: 'budget',
    level: 'bachelor',
    curator_id: '1',
    curator_name: 'Raximov Sherzod Akbarovich',
    student_count: 30,
    active: true,
    created_at: '2024-09-01T00:00:00Z',
  },
]

// ============================================
// MOCK GRADES
// ============================================

export const mockGrades: Grade[] = [
  {
    id: '1',
    student_id: '1',
    student_name: 'Abdullayev Akmal',
    subject_id: '1',
    subject_name: 'Web dasturlash',
    semester: 5,
    education_year: '2023-2024',
    midterm_1: 18,
    midterm_2: 20,
    midterm_avg: 19,
    current_1: 8,
    current_2: 9,
    current_3: 9,
    current_avg: 26,
    final_exam: 42,
    total: 87,
    grade: 'A',
    credit: 6,
    status: 'passed',
    retake_count: 0,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '2',
    student_id: '2',
    student_name: 'Karimova Madina',
    subject_id: '1',
    subject_name: 'Web dasturlash',
    semester: 5,
    education_year: '2023-2024',
    midterm_1: 20,
    midterm_2: 19,
    midterm_avg: 19.5,
    current_1: 10,
    current_2: 10,
    current_3: 10,
    current_avg: 30,
    final_exam: 45,
    total: 94.5,
    grade: 'A',
    credit: 6,
    status: 'passed',
    retake_count: 0,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '3',
    student_id: '3',
    student_name: 'Yusupov Bobur',
    subject_id: '2',
    subject_name: 'Ma\'lumotlar bazasi',
    semester: 3,
    education_year: '2023-2024',
    midterm_1: 14,
    midterm_2: 16,
    midterm_avg: 15,
    current_1: 7,
    current_2: 8,
    current_3: 7,
    current_avg: 22,
    final_exam: 35,
    total: 72,
    grade: 'B',
    credit: 5,
    status: 'passed',
    retake_count: 0,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
]

// ============================================
// MOCK DASHBOARD STATS
// ============================================

export const mockDashboardStats: DashboardStats = {
  total_students: 2547,
  active_students: 2431,
  total_teachers: 187,
  total_subjects: 342,
  average_gpa: 4.12,
  attendance_rate: 87.5,
  payment_rate: 92.3,
}

// ============================================
// MOCK CHART DATA
// ============================================

export const mockStudentsByFaculty: ChartData[] = [
  { name: 'Informatika', value: 850, color: '#0ea5e9' },
  { name: 'Tibbiyot', value: 520, color: '#ec4899' },
  { name: 'Matematika', value: 380, color: '#a855f7' },
  { name: 'Iqtisodiyot', value: 445, color: '#10b981' },
  { name: 'Falsafa', value: 352, color: '#f59e0b' },
]

export const mockStudentsByCourse: ChartData[] = [
  { name: '1-kurs', value: 720 },
  { name: '2-kurs', value: 650 },
  { name: '3-kurs', value: 580 },
  { name: '4-kurs', value: 597 },
]

export const mockGPADistribution: ChartData[] = [
  { name: 'A (86-100)', value: 450, color: '#22c55e' },
  { name: 'B (71-85)', value: 880, color: '#10b981' },
  { name: 'C (55-70)', value: 920, color: '#f59e0b' },
  { name: 'F (0-54)', value: 297, color: '#ef4444' },
]

export const mockPaymentStats: ChartData[] = [
  { name: 'To\'langan', value: 1850, color: '#22c55e' },
  { name: 'Qisman', value: 430, color: '#f59e0b' },
  { name: 'Qarzdor', value: 267, color: '#ef4444' },
]

// ============================================
// MOCK SUBJECTS
// ============================================

export const mockSubjects: Subject[] = [
  {
    id: '1',
    code: 'CS301',
    name: 'Web dasturlash',
    name_en: 'Web Programming',
    credit: 6,
    total_hours: 180,
    lecture_hours: 30,
    practice_hours: 30,
    lab_hours: 30,
    independent_hours: 90,
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    semester: 5,
    is_mandatory: true,
    description: 'Zamonaviy web texnologiyalar va frameworklar',
    created_at: '2021-09-01T00:00:00Z',
    updated_at: '2024-09-01T00:00:00Z',
  },
  {
    id: '2',
    code: 'CS202',
    name: 'Ma\'lumotlar bazasi',
    name_en: 'Database Systems',
    credit: 5,
    total_hours: 150,
    lecture_hours: 30,
    practice_hours: 30,
    lab_hours: 20,
    independent_hours: 70,
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    semester: 3,
    is_mandatory: true,
    description: 'Relatsion va NoSQL ma\'lumotlar bazalari',
    created_at: '2021-09-01T00:00:00Z',
    updated_at: '2024-09-01T00:00:00Z',
  },
]

// ============================================
// MOCK TEACHERS
// ============================================

export const mockTeachers: Teacher[] = [
  {
    id: '1',
    employee_number: 'T001',
    first_name: 'Raximov',
    second_name: 'Sherzod',
    third_name: 'Akbarovich',
    full_name: 'Raximov Sherzod Akbarovich',
    birth_date: '1980-06-15',
    gender: 'male',
    phone: '+998901111111',
    email: 'sherzod.raximov@univer.uz',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sherzod',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    position: 'Katta o\'qituvchi',
    academic_degree: 'phd',
    academic_title: 'docent',
    employment_type: 'full_time',
    hire_date: '2010-09-01',
    work_rate: 1.0,
    status: 'active',
    created_at: '2010-09-01T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
  {
    id: '2',
    employee_number: 'T002',
    first_name: 'Karimova',
    second_name: 'Feruza',
    third_name: 'Bakhtiyorovna',
    full_name: 'Karimova Feruza Bakhtiyorovna',
    birth_date: '1985-03-20',
    gender: 'female',
    phone: '+998902222222',
    email: 'feruza.karimova@univer.uz',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Feruza',
    department: 'Dasturiy injiniring',
    faculty: 'Informatika va dasturlash',
    position: 'Professor',
    academic_degree: 'dsc',
    academic_title: 'professor',
    employment_type: 'full_time',
    hire_date: '2008-09-01',
    work_rate: 1.0,
    status: 'active',
    created_at: '2008-09-01T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
]

// ============================================
// MOCK CONTRACTS
// ============================================

export const mockContracts: Contract[] = [
  {
    id: '1',
    contract_number: 'D-2024-001',
    student_id: '2',
    student_name: 'Karimova Madina',
    contract_date: '2024-08-15',
    contract_sum: 24000000,
    paid_sum: 18000000,
    debt_sum: 6000000,
    discount_percent: 0,
    summa_1: 6000000,
    summa_2: 6000000,
    summa_3: 6000000,
    summa_4: 6000000,
    date_1: '2024-09-01',
    date_2: '2024-11-01',
    date_3: '2025-01-15',
    date_4: '2025-04-01',
    status: 'active',
    created_at: '2024-08-15T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
  {
    id: '2',
    contract_number: 'D-2024-045',
    student_id: '4',
    student_name: 'Nurmatova Dilnoza',
    contract_date: '2024-08-15',
    contract_sum: 24000000,
    paid_sum: 24000000,
    debt_sum: 0,
    discount_percent: 10,
    summa_1: 5400000,
    summa_2: 5400000,
    summa_3: 5400000,
    summa_4: 5400000,
    date_1: '2024-09-01',
    date_2: '2024-11-01',
    date_3: '2025-01-15',
    date_4: '2025-04-01',
    status: 'active',
    created_at: '2024-08-15T00:00:00Z',
    updated_at: '2024-10-19T00:00:00Z',
  },
]

// ============================================
// MOCK PAYMENTS
// ============================================

export const mockPayments: Payment[] = [
  {
    id: '1',
    student_id: '2',
    student_name: 'Karimova Madina',
    contract_id: '1',
    payment_date: '2024-09-01',
    amount: 6000000,
    payment_type: 'payme',
    payment_purpose: '1-to\'lov',
    receipt_number: 'PAY-001-2024',
    status: 'confirmed',
    created_by: 'Admin',
    created_at: '2024-09-01T10:30:00Z',
  },
  {
    id: '2',
    student_id: '2',
    student_name: 'Karimova Madina',
    contract_id: '1',
    payment_date: '2024-11-01',
    amount: 6000000,
    payment_type: 'click',
    payment_purpose: '2-to\'lov',
    receipt_number: 'CLK-045-2024',
    status: 'confirmed',
    created_by: 'Admin',
    created_at: '2024-11-01T14:15:00Z',
  },
  {
    id: '3',
    student_id: '2',
    student_name: 'Karimova Madina',
    contract_id: '1',
    payment_date: '2024-11-15',
    amount: 6000000,
    payment_type: 'uzum',
    payment_purpose: '3-to\'lov',
    receipt_number: 'UZM-122-2024',
    status: 'confirmed',
    created_by: 'Admin',
    created_at: '2024-11-15T09:20:00Z',
  },
]

// ============================================
// MOCK EXAMS
// ============================================

export const mockExams: Exam[] = [
  {
    id: '1',
    subject_id: '1',
    subject_name: 'Web dasturlash',
    group_id: '1',
    group_name: '310-22',
    teacher_id: '1',
    teacher_name: 'Raximov Sherzod',
    exam_type: 'final',
    exam_date: '2024-12-20',
    exam_time: '09:00',
    duration: 120,
    room: '305',
    building: '1-bino',
    max_students: 30,
    registered_students: 25,
    semester: 5,
    education_year: '2024-2025',
    status: 'scheduled',
    created_at: '2024-10-01T00:00:00Z',
  },
  {
    id: '2',
    subject_id: '2',
    subject_name: 'Ma\'lumotlar bazasi',
    group_id: '2',
    group_name: '220-23',
    teacher_id: '2',
    teacher_name: 'Karimova Feruza',
    exam_type: 'midterm',
    exam_date: '2024-11-05',
    exam_time: '14:00',
    duration: 90,
    room: '208',
    building: '2-bino',
    max_students: 30,
    registered_students: 28,
    semester: 3,
    education_year: '2024-2025',
    status: 'scheduled',
    created_at: '2024-10-01T00:00:00Z',
  },
]

// ============================================
// MOCK DIPLOMAS
// ============================================

export const mockDiplomas: Diploma[] = [
  {
    id: '1',
    student_id: 'grad-001',
    student_name: 'Tursunov Jamshid Anvarovich',
    diploma_series: 'BA',
    diploma_number: '123456',
    registration_number: 'REG-2024-001',
    issue_date: '2024-07-01',
    specialty_code: '5350400',
    specialty_name: 'Dasturiy injiniring',
    qualification: 'Dasturiy injinir',
    gpa: 4.5,
    honors: true,
    thesis_topic: 'Mikroservislar arxitekturasida web ilovalarni yaratish',
    thesis_grade: 95,
    status: 'issued',
    created_at: '2024-07-01T00:00:00Z',
  },
]

// ============================================
// MOCK PERFORMANCE RECORDS
// ============================================

export const mockPerformanceRecords: PerformanceRecord[] = [
  {
    id: '1',
    student_id: '1',
    student_name: 'Abdullayev Akmal Anvarovich',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Akmal',
    subject_id: '1',
    subject_name: 'Web dasturlash',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 19,
    current_score: 26,
    final_exam_score: 42,
    total_score: 87,
    grade: 'A',
    credit: 6,
    status: 'passed',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '2',
    student_id: '2',
    student_name: 'Karimova Madina Rustamovna',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Madina',
    subject_id: '1',
    subject_name: 'Web dasturlash',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 19.5,
    current_score: 30,
    final_exam_score: 45,
    total_score: 94.5,
    grade: 'A',
    credit: 6,
    status: 'passed',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '3',
    student_id: '3',
    student_name: 'Toshev Bobur Alisher o\'g\'li',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bobur',
    subject_id: '2',
    subject_name: 'Ma\'lumotlar bazasi',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 17,
    current_score: 24,
    final_exam_score: 38,
    total_score: 79,
    grade: 'B',
    credit: 4,
    status: 'passed',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '4',
    student_id: '4',
    student_name: 'Nurmatova Dilnoza Shavkatovna',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dilnoza',
    subject_id: '2',
    subject_name: 'Ma\'lumotlar bazasi',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 18.5,
    current_score: 28,
    final_exam_score: 41,
    total_score: 87.5,
    grade: 'A',
    credit: 4,
    status: 'passed',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '5',
    student_id: '5',
    student_name: 'Rahimov Jasur Otabek o\'g\'li',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jasur',
    subject_id: '3',
    subject_name: 'Algoritmlar va ma\'lumotlar tuzilmalari',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 16,
    current_score: 22,
    final_exam_score: 35,
    total_score: 73,
    grade: 'C',
    credit: 5,
    status: 'passed',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '6',
    student_id: '6',
    student_name: 'Saidova Malika Azizovna',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Malika',
    subject_id: '3',
    subject_name: 'Algoritmlar va ma\'lumotlar tuzilmalari',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 20,
    current_score: 29,
    final_exam_score: 46,
    total_score: 95,
    grade: 'A',
    credit: 5,
    status: 'passed',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '7',
    student_id: '7',
    student_name: 'Umarov Sardor Bekzod o\'g\'li',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sardor',
    subject_id: '4',
    subject_name: 'Kompyuter tarmoqlari',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 15,
    current_score: 20,
    final_exam_score: 32,
    total_score: 67,
    grade: 'D',
    credit: 3,
    status: 'retake',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
  {
    id: '8',
    student_id: '8',
    student_name: 'Xolmatova Nigora Shodiyevna',
    student_photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nigora',
    subject_id: '4',
    subject_name: 'Kompyuter tarmoqlari',
    semester: 5,
    education_year: '2024-2025',
    midterm_score: 19,
    current_score: 27,
    final_exam_score: 43,
    total_score: 89,
    grade: 'A',
    credit: 3,
    status: 'passed',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-20T00:00:00Z',
  },
]

