import type { Decree, Transfer, DecreeStats } from '@/lib/types/decree'

export const mockDecrees: Decree[] = [
  {
    id: '1',
    decree_number: 'B-125',
    decree_date: '2024-09-01',
    decree_type: 'enrollment',
    title: '2024-2025 o\'quv yiliga talabalarni qabul qilish to\'g\'risida',
    description: '1-kurs talabalarini bakalavriatura ta\'limiga qabul qilish',
    students: [
      {
        id: '1',
        decree_id: '1',
        student_id: 'S001',
        student_name: 'Rahimov Sherzod Abdullayevich',
        student_id_number: '12345',
        group_name: 'IT-101',
        faculty_name: 'Axborot texnologiyalari fakulteti',
      },
    ],
    status: 'approved',
    created_by: 'admin1',
    created_by_name: 'Administrator',
    approved_by: 'rector1',
    approved_by_name: 'Prof. Gulomov S.S.',
    approved_at: '2024-09-02T10:00:00Z',
    created_at: '2024-08-25T14:30:00Z',
    updated_at: '2024-09-02T10:00:00Z',
  },
  {
    id: '2',
    decree_number: 'B-156',
    decree_date: '2024-10-15',
    decree_type: 'transfer',
    title: 'Talabalarni boshqa guruhga ko\'chirish to\'g\'risida',
    description: 'Akademik qarzdorlik sabali guruhdan-guruhga ko\'chirish',
    students: [
      {
        id: '2',
        decree_id: '2',
        student_id: 'S002',
        student_name: 'Karimova Dilnoza Shavkatovna',
        student_id_number: '12346',
        group_name: 'IT-201 → IT-202',
        faculty_name: 'Axborot texnologiyalari fakulteti',
        reason: 'Akademik qarzdorlik',
      },
    ],
    status: 'pending',
    created_by: 'dean1',
    created_by_name: 'Prof. Alimov J.A.',
    created_at: '2024-10-14T09:00:00Z',
    updated_at: '2024-10-14T09:00:00Z',
  },
  {
    id: '3',
    decree_number: 'B-178',
    decree_date: '2024-11-20',
    decree_type: 'academic-leave',
    title: 'Akademik ta\'tilga jo\'natish to\'g\'risida',
    description: 'Sog\'liq holati sababli akademik ta\'til',
    students: [
      {
        id: '3',
        decree_id: '3',
        student_id: 'S003',
        student_name: 'Yusupov Sardor Bekzodovich',
        student_id_number: '12347',
        group_name: 'CE-301',
        faculty_name: 'Kompyuter injiniringi fakulteti',
        reason: 'Tibbiy sabab',
      },
    ],
    status: 'approved',
    created_by: 'dean2',
    created_by_name: 'Prof. Karimov O.R.',
    approved_by: 'rector1',
    approved_by_name: 'Prof. Gulomov S.S.',
    approved_at: '2024-11-21T11:00:00Z',
    created_at: '2024-11-19T15:00:00Z',
    updated_at: '2024-11-21T11:00:00Z',
  },
  {
    id: '4',
    decree_number: 'B-189',
    decree_date: '2024-12-01',
    decree_type: 'graduation',
    title: '2024-yil bitiruv to\'g\'risida',
    description: 'Bakalavriatura bitiruvchilarini ro\'yxatga olish',
    students: [
      {
        id: '4',
        decree_id: '4',
        student_id: 'S004',
        student_name: 'Ismailov Jahongir Rustamovich',
        student_id_number: '12348',
        group_name: 'IT-401',
        faculty_name: 'Axborot texnologiyalari fakulteti',
      },
    ],
    status: 'draft',
    created_by: 'dean1',
    created_by_name: 'Prof. Alimov J.A.',
    created_at: '2024-11-28T10:00:00Z',
    updated_at: '2024-11-28T10:00:00Z',
  },
]

export const mockTransfers: Transfer[] = [
  {
    id: '1',
    transfer_type: 'group',
    student_id: 'S005',
    student_name: 'Abdullayev Aziz Olimovich',
    student_id_number: '12349',
    from_group_id: 'G101',
    from_group_name: 'IT-201',
    to_group_id: 'G102',
    to_group_name: 'IT-202',
    transfer_date: '2024-10-01',
    reason: 'Akademik qarzdorlik bartaraf etish',
    decree_id: '2',
    decree_number: 'B-156',
    status: 'approved',
    created_by: 'dean1',
    created_by_name: 'Prof. Alimov J.A.',
    approved_by: 'rector1',
    approved_by_name: 'Prof. Gulomov S.S.',
    approved_at: '2024-10-02T10:00:00Z',
    created_at: '2024-09-28T14:00:00Z',
    updated_at: '2024-10-02T10:00:00Z',
  },
  {
    id: '2',
    transfer_type: 'course',
    student_id: 'S006',
    student_name: 'Tursunova Nilufar Shavkatovna',
    student_id_number: '12350',
    from_course: 2,
    to_course: 3,
    from_group_id: 'G201',
    from_group_name: 'CE-201',
    to_group_id: 'G301',
    to_group_name: 'CE-301',
    transfer_date: '2024-09-15',
    reason: 'Barcha fanlarni muvaffaqiyatli topshirdi',
    status: 'completed',
    created_by: 'dean2',
    created_by_name: 'Prof. Karimov O.R.',
    approved_by: 'rector1',
    approved_by_name: 'Prof. Gulomov S.S.',
    approved_at: '2024-09-16T09:00:00Z',
    created_at: '2024-09-14T11:00:00Z',
    updated_at: '2024-09-16T09:00:00Z',
  },
  {
    id: '3',
    transfer_type: 'faculty',
    student_id: 'S007',
    student_name: 'Karimov Sardor Anvarovich',
    student_id_number: '12351',
    from_faculty_id: 'F1',
    from_faculty_name: 'Axborot texnologiyalari fakulteti',
    to_faculty_id: 'F2',
    to_faculty_name: 'Kompyuter injiniringi fakulteti',
    from_group_id: 'G101',
    from_group_name: 'IT-201',
    to_group_id: 'G201',
    to_group_name: 'CE-201',
    transfer_date: '2024-11-01',
    reason: 'Shaxsiy ariza asosida',
    status: 'pending',
    created_by: 'dean1',
    created_by_name: 'Prof. Alimov J.A.',
    created_at: '2024-10-28T13:00:00Z',
    updated_at: '2024-10-28T13:00:00Z',
  },
]

export const mockDecreeStats: DecreeStats = {
  total_decrees: 189,
  pending_decrees: 12,
  approved_decrees: 165,
  this_month_count: 8,
  by_type: {
    enrollment: 45,
    transfer: 38,
    expulsion: 15,
    graduation: 42,
    academic_leave: 28,
    restore: 21,
  },
}

