import type {
  Employee,
  TeacherWorkload,
  AcademicDegree,
  AcademicRank,
  EmployeeStats,
} from '@/lib/types/employee'

export const mockEmployees: Employee[] = [
  {
    id: '1',
    employee_id_number: 'EMP-2020-001',
    first_name: 'Jasur',
    last_name: 'Alimov',
    middle_name: 'Abdullayevich',
    full_name: 'Alimov Jasur Abdullayevich',
    birth_date: '1975-05-15',
    gender: 'male',
    phone: '+998 90 123-45-67',
    email: 'j.alimov@tuit.uz',
    address: 'Toshkent shahar, Yunusobod tumani',
    photo: '',
    position: 'Dekan',
    position_uz: 'Dekan',
    department_id: '1',
    department_name: 'Dasturiy injiniring kafedrasi',
    faculty_id: '1',
    faculty_name: 'Axborot texnologiyalari fakulteti',
    employment_type: 'full-time',
    employment_date: '2010-09-01',
    academic_degree_id: '3',
    academic_degree: 'Fan doktori (PhD)',
    academic_rank_id: '2',
    academic_rank: 'Professor',
    is_teacher: true,
    is_foreign: false,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    employee_id_number: 'EMP-2019-042',
    first_name: 'Aziz',
    last_name: 'Yuldashev',
    middle_name: 'Rustamovich',
    full_name: 'Yuldashev Aziz Rustamovich',
    birth_date: '1980-03-20',
    gender: 'male',
    phone: '+998 90 234-56-78',
    email: 'a.yuldashev@tuit.uz',
    position: 'Kafedra mudiri',
    position_uz: 'Kafedra mudiri',
    department_id: '2',
    department_name: 'Sun\'iy intellekt kafedrasi',
    faculty_id: '1',
    faculty_name: 'Axborot texnologiyalari fakulteti',
    employment_type: 'full-time',
    employment_date: '2015-09-01',
    academic_degree_id: '3',
    academic_degree: 'Fan doktori (PhD)',
    academic_rank_id: '1',
    academic_rank: 'Dotsent',
    is_teacher: true,
    is_foreign: false,
    status: 'active',
    created_at: '2019-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    employee_id_number: 'EMP-2021-087',
    first_name: 'Nodira',
    last_name: 'Karimova',
    middle_name: 'Shavkatovna',
    full_name: 'Karimova Nodira Shavkatovna',
    birth_date: '1985-07-10',
    gender: 'female',
    phone: '+998 90 345-67-89',
    email: 'n.karimova@tuit.uz',
    position: 'Katta o\'qituvchi',
    position_uz: 'Katta o\'qituvchi',
    department_id: '1',
    department_name: 'Dasturiy injiniring kafedrasi',
    faculty_id: '1',
    faculty_name: 'Axborot texnologiyalari fakulteti',
    employment_type: 'full-time',
    employment_date: '2018-09-01',
    academic_degree_id: '2',
    academic_degree: 'Falsafa doktori (PhD)',
    is_teacher: true,
    is_foreign: false,
    status: 'active',
    created_at: '2021-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    employee_id_number: 'EMP-2020-125',
    first_name: 'Bekzod',
    last_name: 'Tursunov',
    middle_name: 'Olimovich',
    full_name: 'Tursunov Bekzod Olimovich',
    birth_date: '1978-11-25',
    gender: 'male',
    phone: '+998 90 456-78-90',
    email: 'b.tursunov@tuit.uz',
    position: 'O\'qituvchi',
    position_uz: 'O\'qituvchi',
    department_id: '3',
    department_name: 'Kompyuter tizimlari kafedrasi',
    faculty_id: '2',
    faculty_name: 'Kompyuter injiniringi fakulteti',
    employment_type: 'full-time',
    employment_date: '2012-09-01',
    academic_degree_id: '2',
    academic_degree: 'Falsafa doktori (PhD)',
    is_teacher: true,
    is_foreign: false,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    employee_id_number: 'EMP-2022-203',
    first_name: 'Malika',
    last_name: 'Rahimova',
    middle_name: 'Anvarovna',
    full_name: 'Rahimova Malika Anvarovna',
    birth_date: '1990-02-14',
    gender: 'female',
    phone: '+998 90 567-89-01',
    email: 'm.rahimova@tuit.uz',
    position: 'Laborant',
    position_uz: 'Laborant',
    department_id: '1',
    department_name: 'Dasturiy injiniring kafedrasi',
    faculty_id: '1',
    faculty_name: 'Axborot texnologiyalari fakulteti',
    employment_type: 'full-time',
    employment_date: '2022-09-01',
    is_teacher: false,
    is_foreign: false,
    status: 'active',
    created_at: '2022-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockTeacherWorkloads: TeacherWorkload[] = [
  {
    teacher_id: '1',
    academic_year: '2024-2025',
    total_hours: 850,
    lecture_hours: 320,
    practice_hours: 280,
    lab_hours: 150,
    seminar_hours: 60,
    consultation_hours: 30,
    exam_hours: 10,
    other_hours: 0,
    status: 'approved',
    updated_at: '2024-09-01T00:00:00Z',
  },
  {
    teacher_id: '2',
    academic_year: '2024-2025',
    total_hours: 920,
    lecture_hours: 360,
    practice_hours: 300,
    lab_hours: 180,
    seminar_hours: 50,
    consultation_hours: 20,
    exam_hours: 10,
    other_hours: 0,
    status: 'approved',
    updated_at: '2024-09-01T00:00:00Z',
  },
  {
    teacher_id: '3',
    academic_year: '2024-2025',
    total_hours: 720,
    lecture_hours: 240,
    practice_hours: 280,
    lab_hours: 120,
    seminar_hours: 50,
    consultation_hours: 20,
    exam_hours: 10,
    other_hours: 0,
    status: 'planned',
    updated_at: '2024-09-01T00:00:00Z',
  },
  {
    teacher_id: '4',
    academic_year: '2024-2025',
    total_hours: 1050,
    lecture_hours: 420,
    practice_hours: 360,
    lab_hours: 180,
    seminar_hours: 60,
    consultation_hours: 20,
    exam_hours: 10,
    other_hours: 0,
    status: 'approved',
    updated_at: '2024-09-01T00:00:00Z',
  },
]

export const mockAcademicDegrees: AcademicDegree[] = [
  {
    id: '1',
    code: 'BACHELOR',
    name: 'Bakalavr',
    name_uz: 'Bakalavr',
    name_ru: 'Бакалавр',
    name_en: 'Bachelor',
    level: 1,
    description: 'Bakalavr darajasi',
    status: 'active',
  },
  {
    id: '2',
    code: 'PHD',
    name: 'Falsafa doktori (PhD)',
    name_uz: 'Falsafa doktori (PhD)',
    name_ru: 'Доктор философии (PhD)',
    name_en: 'Doctor of Philosophy (PhD)',
    level: 3,
    description: 'Falsafa doktori ilmiy darajasi',
    status: 'active',
  },
  {
    id: '3',
    code: 'DSC',
    name: 'Fan doktori (DSc)',
    name_uz: 'Fan doktori (DSc)',
    name_ru: 'Доктор наук (DSc)',
    name_en: 'Doctor of Science (DSc)',
    level: 4,
    description: 'Fan doktori ilmiy darajasi',
    status: 'active',
  },
]

export const mockAcademicRanks: AcademicRank[] = [
  {
    id: '1',
    code: 'DOTSENT',
    name: 'Dotsent',
    name_uz: 'Dotsent',
    name_ru: 'Доцент',
    name_en: 'Associate Professor',
    level: 1,
    status: 'active',
  },
  {
    id: '2',
    code: 'PROFESSOR',
    name: 'Professor',
    name_uz: 'Professor',
    name_ru: 'Профессор',
    name_en: 'Professor',
    level: 2,
    status: 'active',
  },
]

export const mockEmployeeStats: EmployeeStats = {
  total_count: 450,
  active_count: 420,
  teachers_count: 260,
  full_time_count: 380,
  part_time_count: 50,
  with_degree_count: 180,
  foreign_count: 12,
}

