import type { University, Faculty, Department, StructureStats } from '@/lib/types/structure'

export const mockUniversity: University = {
  id: '1',
  code: 'UNI-001',
  name: "Toshkent Axborot Texnologiyalari Universiteti",
  name_uz: "Toshkent Axborot Texnologiyalari Universiteti",
  name_ru: "Ташкентский Университет Информационных Технологий",
  name_en: "Tashkent University of Information Technologies",
  short_name: 'TATU',
  inn: '123456789',
  address: "Amir Temur shox ko'chasi 108, Toshkent, O'zbekiston",
  phone: '+998 71 238-42-42',
  email: 'info@tuit.uz',
  website: 'https://tuit.uz',
  rector_name: "Prof. Gulomov Sirojiddin Saidaxrorovich",
  rector_phone: '+998 71 238-42-00',
  logo: '',
  description: "Toshkent Axborot Texnologiyalari Universiteti - O'zbekistonda axborot texnologiyalari sohasida yetakchi oliy ta'lim muassasasi",
  description_uz: "TATU O'zbekistonda IT sohasida eng yirik universitet",
  description_ru: "ТУИТ - ведущий университет в области информационных технологий",
  description_en: "TUIT - Leading university in IT field",
  established_year: 1955,
  status: 'active',
  created_at: '2020-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
}

export const mockFaculties: Faculty[] = [
  {
    id: '1',
    code: 'FAC-IT',
    name: 'Axborot texnologiyalari fakulteti',
    name_uz: 'Axborot texnologiyalari fakulteti',
    name_ru: 'Факультет информационных технологий',
    name_en: 'Faculty of Information Technologies',
    short_name: 'IT',
    university_id: '1',
    dean_id: '101',
    dean_name: 'Prof. Alimov Jasur Abdullayevich',
    dean_phone: '+998 71 238-45-67',
    dean_email: 'j.alimov@tuit.uz',
    location: '1-bino, 3-qavat',
    description: 'Dasturiy ta\'minot va tizim dasturlash',
    students_count: 1250,
    teachers_count: 85,
    departments_count: 5,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    code: 'FAC-CS',
    name: 'Kompyuter injiniringi fakulteti',
    name_uz: 'Kompyuter injiniringi fakulteti',
    name_ru: 'Факультет компьютерной инженерии',
    name_en: 'Faculty of Computer Engineering',
    short_name: 'CE',
    university_id: '1',
    dean_id: '102',
    dean_name: 'Prof. Karimov Otabek Rustamovich',
    dean_phone: '+998 71 238-45-68',
    dean_email: 'o.karimov@tuit.uz',
    location: '2-bino, 2-qavat',
    description: 'Kompyuter tizimlari va tarmoqlari',
    students_count: 980,
    teachers_count: 72,
    departments_count: 4,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    code: 'FAC-TK',
    name: 'Telekommunikatsiya texnologiyalari fakulteti',
    name_uz: 'Telekommunikatsiya texnologiyalari fakulteti',
    name_ru: 'Факультет телекоммуникационных технологий',
    name_en: 'Faculty of Telecommunication Technologies',
    short_name: 'TT',
    university_id: '1',
    dean_id: '103',
    dean_name: 'Prof. Nazarov Dilshod Anvarovich',
    dean_phone: '+998 71 238-45-69',
    dean_email: 'd.nazarov@tuit.uz',
    location: '3-bino, 1-qavat',
    description: 'Mobil aloqa va radio texnikalar',
    students_count: 750,
    teachers_count: 58,
    departments_count: 3,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    code: 'FAC-TV',
    name: 'Televideniye texnologiyalari fakulteti',
    name_uz: 'Televideniye texnologiyalari fakulteti',
    name_ru: 'Факультет телевизионных технологий',
    name_en: 'Faculty of Television Technologies',
    short_name: 'TV',
    university_id: '1',
    dean_id: '104',
    dean_name: 'Prof. Rahimov Sardor Bakhtiyorovich',
    dean_phone: '+998 71 238-45-70',
    dean_email: 's.rahimov@tuit.uz',
    location: '4-bino, 2-qavat',
    description: 'Multimedia va televideniye',
    students_count: 620,
    teachers_count: 45,
    departments_count: 3,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockDepartments: Department[] = [
  {
    id: '1',
    code: 'DEP-SE',
    name: 'Dasturiy injiniring kafedrasi',
    name_uz: 'Dasturiy injiniring kafedrasi',
    name_ru: 'Кафедра программной инженерии',
    name_en: 'Software Engineering Department',
    short_name: 'SE',
    faculty_id: '1',
    faculty_name: 'Axborot texnologiyalari fakulteti',
    head_id: '201',
    head_name: 'Prof. Abdullayev Kamol Shukurovich',
    head_phone: '+998 71 238-46-01',
    head_email: 'k.abdullayev@tuit.uz',
    location: '1-bino, 301-xona',
    description: 'Web, mobile va enterprise dasturlar ishlab chiqish',
    teachers_count: 18,
    subjects_count: 12,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    code: 'DEP-AI',
    name: 'Sun\'iy intellekt kafedrasi',
    name_uz: 'Sun\'iy intellekt kafedrasi',
    name_ru: 'Кафедра искусственного интеллекта',
    name_en: 'Artificial Intelligence Department',
    short_name: 'AI',
    faculty_id: '1',
    faculty_name: 'Axborot texnologiyalari fakulteti',
    head_id: '202',
    head_name: 'Prof. Yuldashev Aziz Rustamovich',
    head_phone: '+998 71 238-46-02',
    head_email: 'a.yuldashev@tuit.uz',
    location: '1-bino, 305-xona',
    description: 'Machine Learning, Deep Learning, Computer Vision',
    teachers_count: 15,
    subjects_count: 10,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    code: 'DEP-CS',
    name: 'Kompyuter tizimlari kafedrasi',
    name_uz: 'Kompyuter tizimlari kafedrasi',
    name_ru: 'Кафедра компьютерных систем',
    name_en: 'Computer Systems Department',
    short_name: 'CS',
    faculty_id: '2',
    faculty_name: 'Kompyuter injiniringi fakulteti',
    head_id: '203',
    head_name: 'Prof. Tursunov Bekzod Olimovich',
    head_phone: '+998 71 238-46-03',
    head_email: 'b.tursunov@tuit.uz',
    location: '2-bino, 201-xona',
    description: 'Mikrokontrollerlar va IoT tizimlari',
    teachers_count: 16,
    subjects_count: 11,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    code: 'DEP-NT',
    name: 'Kompyuter tarmoqlari kafedrasi',
    name_uz: 'Kompyuter tarmoqlari kafedrasi',
    name_ru: 'Кафедра компьютерных сетей',
    name_en: 'Computer Networks Department',
    short_name: 'NT',
    faculty_id: '2',
    faculty_name: 'Kompyuter injiniringi fakulteti',
    head_id: '204',
    head_name: 'Prof. Sharipov Jahongir Nuriddinovich',
    head_phone: '+998 71 238-46-04',
    head_email: 'j.sharipov@tuit.uz',
    location: '2-bino, 205-xona',
    description: 'Tarmoq injiniringi va kiberhavfsizlik',
    teachers_count: 14,
    subjects_count: 9,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    code: 'DEP-TC',
    name: 'Telekommunikatsiya kafedrasi',
    name_uz: 'Telekommunikatsiya kafedrasi',
    name_ru: 'Кафедра телекоммуникаций',
    name_en: 'Telecommunication Department',
    short_name: 'TC',
    faculty_id: '3',
    faculty_name: 'Telekommunikatsiya texnologiyalari fakulteti',
    head_id: '205',
    head_name: 'Prof. Ismoilov Sardor Akmalovich',
    head_phone: '+998 71 238-46-05',
    head_email: 's.ismoilov@tuit.uz',
    location: '3-bino, 101-xona',
    description: 'Mobil aloqa va 5G texnologiyalari',
    teachers_count: 12,
    subjects_count: 8,
    status: 'active',
    created_at: '2020-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockStructureStats: StructureStats = {
  faculties_count: 4,
  departments_count: 5,
  sections_count: 8,
  students_count: 3600,
  teachers_count: 260,
  employees_count: 450,
}

